name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10.8
      uses: actions/setup-python@v4.0.0
      with:
        python-version: 3.10.8
    - name: Install dependencies
      run: |
        pip3 install flake8
    - name: Lint with flake8
      run: |
        pip3 install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pip3 install pytest
        pytest
      env:
        BASE_URL: ${{ secrets.BASE_URL }}
        TEST_STAKEHOLDER: ${{ secrets.TEST_STAKEHOLDER }}
        TEST_DETECTION_ID: ${{ secrets.TEST_DETECTION_ID }}
        TEST_HOST_ID: ${{ secrets.TEST_HOST_ID }}
