name: Python Unit Testing

on:
  push:
    branches:
      - dev

jobs:
  linting:
    runs-on: ubuntu-latest
    environment: dev

    steps:
    - uses: actions/checkout@v3
      with:
        ssh-key: |
          ${{ secrets.SSH_KEY_SOC_DB_UTILS }}
        submodules: recursive
    - name: Set up Python 3.10.8
      uses: actions/setup-python@v4.0.0
      with:
        python-version: 3.10.8
    - name: Install dependencies
      run: |
        pip3 install flake8 -r ./requirements.txt
    - name: Lint with flake8 (critical only)
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    - name: Lint with pylint (verbose)
      run: |
        # Use pylint for verbose testing
        pylint ./vectra/ ./reputation/

  unit-testing:
    runs-on: ubuntu-latest
    environment: dev

    steps:
    - uses: actions/checkout@v3
      with:
        ssh-key: |
          ${{ secrets.SSH_KEY_SOC_DB_UTILS }}
        submodules: recursive
    - name: Set up Python 3.10.8
      uses: actions/setup-python@v4.0.0
      with:
        python-version: 3.10.8
    - name: Install dependencies
      run: |
        pip3 install -r ./requirements.txt
    - name: Test with pytest
      run: |
        pytest
      env:
        VECTRA_API_URL: ${{ secrets.VECTRA_API_URL }}
        TEST_STAKEHOLDER: ${{ secrets.TEST_STAKEHOLDER }}
        TEST_DETECTION_ID: ${{ secrets.TEST_DETECTION_ID }}
        TEST_HOST_ID: ${{ secrets.TEST_HOST_ID }}
        AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        UMBRELLA_API_KEY: ${{ secrets.UMBRELLA_API_KEY }}

